# Generated by Django 4.2 on 2023-05-24 10:05

import bboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_spare_machine_advuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.RemoveField(
            model_name='icecreammarket',
            name='ice_cream',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published', 'title'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[bboard.models.validate_even], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(error_messages={'min_length': 'Слишком мало символов'}, max_length=50, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='AdvUser',
        ),
        migrations.DeleteModel(
            name='IceCream',
        ),
        migrations.DeleteModel(
            name='IceCreamMarket',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
    ]
